defaults: &defaults
  adapter: postgresql
  encoding: unicode
  database: manshar_development
  pool: 5
  username: postgres
  password:

development:
  <<: *defaults

test:
  <<: *defaults
  database: manshar_test

production:
  <<: *defaults
  database: manshar_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV['MAX_THREADS'] || ENV["DB_POOL"] || 5 %>
