language: ruby
env:
  matrix:
  - DISPLAY=:99.0
  global:
  - MANSHAR_HOME=/home/travis/build/manshar/manshar
  - secure: Ek/EsKA4yC6RrhlHNhlSsztud+UxFxbvwiaEkqIo2MTo1ewr40/7k8JLuONgYNHL47/ZKvzqXfRiD+Zq18xIXNEO8KyIf3ASLmhMYOLQsPZIsmCSUgnBpwpfiO9tiuAf4ww5+A8sD4Ob4xnkLpwB961bBn1RyIKN6mymuxzdtPw=
rvm:
  - 2.0.0
  - ruby-head
before_install:
  - cd /usr/lib/git-core/
  - sudo wget https://raw.github.com/apenwarr/git-subtree/master/git-subtree.sh
  - sudo mv git-subtree.sh git-subtree
  - sudo chmod 755 git-subtree
  - cd $MANSHAR_HOME/backend
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs
  - sudo apt-get install redis-server
before_script:
  - cd $MANSHAR_HOME/backend
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database manshar_test;' -U postgres
  - bundle exec rake db:migrate
  - cd $MANSHAR_HOME/web-client
  - npm install grunt --save-dev
  - npm install
  - sh -e /etc/init.d/xvfb start
  - bower install
  - sudo redis-server /etc/redis/redis.conf
bundler_args: --without development
script:
  - cd $MANSHAR_HOME/web-client && grunt test && cd $MANSHAR_HOME/backend && bundle exec rspec
matrix:
  allow_failures:
  - rvm: ruby-head
after_success:
  - cd $MANSHAR_HOME
  - ./utils/travis/deploy.sh
notifications:
  slack: manshar:CPhqeSFN8hlY3duA8vlMzDeB

